### PR TITLE
Added .blade extension to supported fileTypes

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by Ingramz** [comment]
@jbrooksuk I can't remember `.blade` extension being used anywhere or at least documentation not suggesting it. Is it in use somewhere or at least can be used out of the box?

**Comment by jbrooksuk** [comment]
I've definitely seen this somewhere, but I can't remember where now.

**Comment by Ingramz** [comment]
Please do find out. It's a bit dumb if nobody knows why exactly it was added or what it gives.

**Comment by Ingramz** [comment]
I checked and none of the current framework versions (4<) support this.

**Pull request closed without merging**
